### ISSUE TITLE
Distro-independent?

### ISSUE THREAD

**Issue by lionirdeadman** [dhewg/nine#12]
Wouldn't it make more sense to have a list of known paths given by people who want to use it and let users set a ENV variable  for `d3dadapter9.so` (which is why you want distro-dependent builds afaik) if that doesn't work rather than distro-specific builds?

Or offer a way to config it that way all distros can build it the same simply with a different config file (and also allows users to do the same if it's not actually available by their distro).

Why would we do this? If it's not available to people in their distros (or configurable to make it work), they'll be less likely to use it all because they'd need to compile it which goes against the goal of making nine easier to use.

(Option 1 being possibly more OOTB but less configurable by individual distros without forking)

**Comment by dhewg** [comment]
Sounds like there's a slight misunderstanding. When you or your distro builds this project, the path of `d3dadapter9.so` is read via `pkg-config --variable=moduledir d3d` and embedded as default path. So if you build it, you don't have to worry about it at all - that default will work. Same if your distro builds it.

The issue is when you move binaries from one distro to another. Like if I would provide release builds built on Debian, and you download that and use it on e.g. Fedora.

We could add a list of known locations and walk that. But that implies shipping binaries which work everywhere. Independent of the module path, that might not be the case. We're building linux libraries here, and not windows ones like the MinGW version of DXVK. The versions of the libs we link against matter.

That's why I think distro packages are the way to go. They solve all of that, and users can just use their favorite package manager and they get updates through official channels.

**Comment by dhewg** [comment]
As is said, I'm not opposed to make it smarter and try to find that library. But for what? There are no binary releases.

**Comment by dhewg** [comment]
We could use a CI to build releases I guess, which may run on multiple distros (but not guaranteed as mentioned above). With that, a smarter way to find the library would make sense. I'll try to set that up.

**Comment by lionirdeadman** [comment]
Yes, binary releases would be quite nice for people for testing and in general not wait for their distros to update the package. Thank you :)

**Comment by dhewg** [comment]
All done now ;)
https://github.com/iXit/wine-nine-standalone/releases/tag/v0.2
