### ISSUE TITLE
Clarify mixing of different Wine versions

### ISSUE THREAD

**Issue by chewi** [dhewg/nine#6]
I notice the ninewinecfg.exe code has `#if` conditionals on `WINE_STAGING`. It's not clear to me why this is and I'd like to know whether you can build against staging and run against vanilla or vice-versa. If not, I think it would be possible to make this dynamic at runtime? I'm trying to package this up for Gentoo and we allow vanilla and staging to be installed simultaneously. This should be clarified in the README in any case.

**Comment by dhewg** [comment]
Hehe, the code is from the the Gallium Nine WINE tree. There have been unofficial `add-on` packages that used that.
The difference is that the staging code path uses `DllRedirects` instead of `DllOverrides` - the former being a patch set of WINE staging.
But it's unused here, `DllOverrides` is available everywhere, there's no need to use something different - even on WINE staging - so that's what we use here. The code could be removed, I just didn't do that yet to keep the differences to the WINE+Nine tree to a minimum.

**Comment by chewi** [comment]
Awesome, thanks. I've cleared that up in the README.

**Comment by dhewg** [comment]
Nice, thanks!

If gentoo gets a package for this, please ping me and I'll add it to the README (or you do and open a MR).

**Comment by chewi** [comment]
Will do soon.

Because we allow multiple versions of Wine to be installed simultaneously, I found `nine-install.sh` wasn't a very good fit. I therefore patched things to access the DLL via `Z:\usr\lib(32|64)\d3d9-nine.dll.so` and you set it up by calling `wine(64) /usr/lib(32|64)/ninewinecfg.exe.so`. I mention this after installing the package. Hope you don't mind that. It requires a little patching + sed around the cross files but I don't think there's any way you could make that easier for us, unless Meson starts allowing variables.

Are you planning to make any formal releases? I don't know how often this part of the D3D9 code changes.

**Comment by dhewg** [comment]
Of course I don't mind, it's up to you how to package it ;)
I just created #9, so maybe we can improve the install script for all distros.

Format releases are coming soon in the form of tags/tarballs (waiting on some more feedback for different distros).
